### ISSUE TITLE
Support node 18

### ISSUE THREAD

**Issue by groteck** [bacebu4/cobertura#3]
Hi, first thanks for the project I'm testing this reporter but I got an error in node:18.

Error message:
```bash
node:internal/test_runner/harness:48
      throw err;
      ^

TypeError: Cannot read properties of undefined (reading 'reduce')
    at /Users/jlopez/code/work/ci-api-cache/node_modules/.pnpm/cobertura@1.0.2/node_modules/cobertura/index.js:52:45
    at Array.map (<anonymous>)
    at coberturaReporter (/Users/jlopez/code/work/ci-api-cache/node_modules/.pnpm/cobertura@1.0.2/node_modules/cobertura/index.js:47:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async next (node:internal/streams/from:85:11)
Emitted 'error' event on Duplex instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.20.3
 ELIFECYCLE  Command failed with exit code 7.
```

I saw that the reporter is tested at node:21 in your gitlab example so please if I'm wrong and it works in node 18 let me know and I will continue investigating.

**Comment by bacebu4** [comment]
Hi!

The reporter is heavily relies on `branches` and `functions` property of test files. They are defined in [node source code here](https://github.com/nodejs/node/blob/3c5ceff85fb90b265a85270bba38085f45c7f25e/lib/internal/test_runner/coverage.js#L251). But node v18 doesn't have such properties, they would appear in [this push call](https://github.com/nodejs/node/blob/e578c0b1e8d3dd817e692a0c5df1b97580bc7c7f/lib/internal/test_runner/coverage.js#L201)

So it seems like the only way for this reporter to work under node v18 is to backport these changes.

Thanks for bringing up the issue. I'll update the readme of the project with the minimum supported version of node
